# Generated by Django 6.0.1 on 2026-01-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor_range',
            field=models.CharField(choices=[('2-10', '2-10'), ('11-18', '11-18'), ('19-27', '19-27'), ('28-30', '28-30')], default='2-10', max_length=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='orientation',
            field=models.CharField(choices=[('Schneeberg', 'Schneeberg'), ('Inner Stadt', 'Inner Stadt'), ('Sonnenaufgang', 'Sonnenaufgang'), ('Prater', 'Prater')], default='Schneeberg', max_length=50),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tower',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], default='I', max_length=3),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
