# Generated by Django 6.0.1 on 2026-01-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apartment_floor_range_apartment_orientation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apartments/'),
        ),
    ]
