# Generated by Django 6.0.1 on 2026-01-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='floor',
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor_area',
            field=models.PositiveIntegerField(default=0, help_text='Square meters'),
            preserve_default=False,
        ),
    ]
