# Generated by Django 6.0.1 on 2026-01-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_apartment_floor_apartment_floor_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
