# Generated by Django 6.0.1 on 2026-01-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_apartment_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='phone',
        ),
    ]
