# Generated by Django 6.0.1 on 2026-01-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_inquiry_agree_inquiry_commercial_inquiry_housing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='outdoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='press',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='print_ad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
